# Generated by Django 5.0 on 2025-08-09 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company name')),
            ],
            options={
                'verbose_name': 'Company name',
                'verbose_name_plural': 'companies name',
            },
        ),
        migrations.CreateModel(
            name='DayFormatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=255, unique=True, verbose_name='day format')),
            ],
            options={
                'verbose_name': 'day format',
                'verbose_name_plural': 'day formats',
            },
        ),
        migrations.CreateModel(
            name='PdfReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_files', verbose_name='PDF')),
                ('start_date', models.DateField(verbose_name='Start dateTime')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End dateTime')),
                ('cycle', models.CharField(choices=[('1', 'cycle 1'), ('2', 'cycle 2')], max_length=5, verbose_name='cycle')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='pdfreportapp.companymodel')),
                ('days_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format', to='pdfreportapp.dayformatmodel')),
            ],
            options={
                'verbose_name': 'Pdf',
                'verbose_name_plural': 'Pdf',
            },
        ),
    ]
