# Generated by Django 5.0 on 2025-08-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreportapp', '0001_initial'),
        ('projectapp', '0008_projectmodel_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfreportmodel',
            name='days_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.dayformatmodel'),
        ),
        migrations.DeleteModel(
            name='DayFormatModel',
        ),
    ]
