# Generated by Django 5.0 on 2025-08-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfreportapp', '0002_alter_pdfreportmodel_days_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfreportmodel',
            name='end_date',
        ),
    ]
