# Generated by Django 5.0 on 2025-08-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectapp', '0019_alter_projectmodel_latest_pdf_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the employer')),
                ('phone_number', models.CharField(help_text="Employer's mobile phone", max_length=16, verbose_name='phone number')),
                ('through', models.CharField(help_text='like whats app, phone, SMS or some thing else.', max_length=255, verbose_name='How to declare?')),
                ('date', models.DateField(verbose_name='date')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='projectapp.projectmodel', verbose_name='project')),
            ],
            options={
                'verbose_name': 'Feed Back',
                'verbose_name_plural': 'Feed Backs',
            },
        ),
        migrations.CreateModel(
            name='FeedBackResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('through', models.CharField(help_text='like whats app, phone, SMS or some thing else.', max_length=255, verbose_name='How to declare?')),
                ('date', models.DateField(verbose_name='date')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedbacks/<function file_path at 0x000002688A3285E0>')),
                ('iso_form', models.FileField(blank=True, null=True, upload_to='feedbacks/ISO/<function file_path at 0x000002688A3285E0>')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='feedbackapp.feedbackmodel', verbose_name='feedback')),
            ],
            options={
                'verbose_name': 'Feed Back Response',
                'verbose_name_plural': 'Feed Backs Responses',
            },
        ),
    ]
