# Generated by Django 5.0 on 2025-09-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackAttachment',
            new_name='FeedBackAttachmentModel',
        ),
    ]
