# Generated by Django 5.0 on 2025-08-30 10:19

import core.files_path
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponsemodel',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='through',
            field=models.CharField(help_text='like whats app, call, SMS or some thing else.', max_length=255, verbose_name='How to declare?'),
        ),
        migrations.AlterField(
            model_name='feedbackresponsemodel',
            name='iso_form',
            field=models.FileField(blank=True, null=True, upload_to=core.files_path.feedback_ISO_file_path),
        ),
        migrations.AlterField(
            model_name='feedbackresponsemodel',
            name='through',
            field=models.CharField(help_text='like whats app, call, SMS or some thing else.', max_length=255, verbose_name='How to declare?'),
        ),
        migrations.CreateModel(
            name='FeedBackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.files_path.feedback_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedbackapp.feedbackmodel')),
            ],
        ),
    ]
