# Generated by Django 5.0 on 2025-09-06 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_rename_feedbackattachment_feedbackattachmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponsemodel',
            name='feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedbackapp.feedbackmodel', verbose_name='feedback'),
        ),
    ]
