# Generated by Django 5.0 on 2025-09-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_customusermodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
