# Generated by Django 5.0 on 2025-07-19 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company name')),
            ],
            options={
                'verbose_name': 'Company name',
                'verbose_name_plural': 'companies name',
            },
        ),
        migrations.CreateModel(
            name='DayFormatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=255, unique=True, verbose_name='day format')),
            ],
            options={
                'verbose_name': 'day format',
                'verbose_name_plural': 'day formats',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start dateTime')),
                ('end_date', models.DateTimeField(verbose_name='End dateTime')),
                ('start_cycle', models.DateTimeField(choices=[('cycle 1', '1'), ('cycle 2', '2')], verbose_name='Start cycle')),
                ('end_cycle', models.DateTimeField(choices=[('cycle 1', '1'), ('cycle 2', '2')], verbose_name='end cycle')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projectapp.companymodel')),
                ('days_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format', to='projectapp.dayformatmodel')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
