# Generated by Django 5.0 on 2025-08-31 12:25

import core.files_path
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company name')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='DayFormatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=255, unique=True, verbose_name='day format')),
            ],
            options={
                'verbose_name': 'day format',
                'verbose_name_plural': 'day formats',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometry')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_description', models.FileField(blank=True, null=True, upload_to=core.files_path.location_file_path, verbose_name='Image')),
                ('start_date', models.DateField(verbose_name='Start dateTime')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End dateTime')),
                ('total_days', models.PositiveIntegerField(default=0, editable=False, verbose_name='Total number of days')),
                ('start_cycle', models.CharField(choices=[('1', 'cycle 1'), ('2', 'cycle 2')], max_length=5, verbose_name='Start cycle')),
                ('end_cycle', models.CharField(blank=True, choices=[('1', 'cycle 1'), ('2', 'cycle 2')], max_length=5, null=True, verbose_name='End cycle')),
                ('total_cycle', models.PositiveIntegerField(default=0, editable=False, verbose_name='Total cycle')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('is_active_now', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='is_active_now')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_pdf_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Latest PDF path')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projectapp.companymodel')),
                ('days_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format', to='projectapp.dayformatmodel')),
            ],
            options={
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
                'indexes': [models.Index(fields=['company_name'], name='projectapp__company_7a6c50_idx'), models.Index(fields=['location'], name='projectapp__locatio_9afc18_idx'), models.Index(fields=['is_active_now'], name='projectapp__is_acti_5d24f1_idx'), models.Index(fields=['company_name', 'location'], name='projectapp__company_aed6b9_idx')],
            },
        ),
    ]
