# Generated by Django 5.0 on 2025-07-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='end_cycle',
            field=models.DateField(choices=[('1', 'cycle 1'), ('2', 'cycle 2')], verbose_name='end cycle'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='start_cycle',
            field=models.DateField(choices=[('1', 'cycle 1'), ('2', 'cycle 2')], verbose_name='Start cycle'),
        ),
    ]
