# Generated by Django 5.0 on 2025-09-03 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(help_text='format Input: Point → Lat,Lon | Line → Lat1,Lon1; Lat2,Lon2; Lat3,Lon3; ...', srid=4326, verbose_name='Geometry'),
        ),
        migrations.AddConstraint(
            model_name='projectmodel',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='end_not_befor_start'),
        ),
        migrations.AddConstraint(
            model_name='projectmodel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_cycle__isnull', True), ('end_date__isnull', True)), models.Q(('end_cycle__isnull', False), ('end_date__isnull', False)), _connector='OR'), name='end_date_cycle_pair_nullity'),
        ),
        migrations.AddConstraint(
            model_name='projectmodel',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_cycle__isnull', True), models.Q(('end_date', models.F('start_date')), _negated=True), ('end_cycle__gte', models.F('start_cycle')), _connector='OR'), name='end_cycle_gte_start_cycle_same_day'),
        ),
    ]
