# Generated by Django 5.0 on 2025-09-07 08:12

import core.files_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_projectmodel_geometry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='image_description',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.files_path.location_file_path, verbose_name='attachment'),
        ),
    ]
