# Generated by Django 5.0 on 2025-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_projectmodel_end_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='end_cycle',
            field=models.CharField(choices=[('1', 'cycle 1'), ('2', 'cycle 2')], max_length=5, verbose_name='end cycle'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='end_date',
            field=models.DateField(verbose_name='End dateTime'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='start_cycle',
            field=models.CharField(choices=[('1', 'cycle 1'), ('2', 'cycle 2')], max_length=5, verbose_name='Start cycle'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='start_date',
            field=models.DateField(verbose_name='Start dateTime'),
        ),
    ]
