# Generated by Django 5.0 on 2025-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_projectmodel_end_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='total_cycle',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total cycle'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='end_cycle',
            field=models.CharField(blank=True, choices=[('1', 'cycle 1'), ('2', 'cycle 2')], max_length=5, null=True, verbose_name='End cycle'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End dateTime'),
        ),
    ]
