# Generated by Django 5.0 on 2025-09-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_remove_projectmodel_image_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFormatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='format name')),
            ],
            options={
                'verbose_name': 'project format',
                'verbose_name_plural': 'project formats',
            },
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='days_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_format', to='projectapp.dayformatmodel'),
        ),
    ]
