# Generated by Django 5.0 on 2025-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_projectmodel_total_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='total_cycle',
            field=models.PositiveIntegerField(default=0, verbose_name='Total cycle'),
        ),
    ]
