# Generated by Django 5.0 on 2025-07-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_alter_projectmodel_total_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='total_cycle',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total cycle'),
        ),
    ]
