# Generated by Django 5.0 on 2025-09-16 10:18

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_projectmodel_project_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location name')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Geometry')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.RenameIndex(
            model_name='projectmodel',
            new_name='projectapp__locatio_4b92f4_idx',
            old_name='projectapp__locatio_9afc18_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmodel',
            new_name='projectapp__company_1b245e_idx',
            old_name='projectapp__company_aed6b9_idx',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='geometry',
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='projectapp.companymodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='days_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='days_format', to='projectapp.dayformatmodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='project_format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project_format', to='projectapp.projectformatmodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location', to='projectapp.locationmodel'),
        ),
    ]
