# Generated by Django 5.0 on 2025-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_projectmodel_total_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='total_days',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total number of days'),
        ),
    ]
