# Generated by Django 5.0 on 2025-09-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_locationmodel_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectmodel',
            name='projectapp__locatio_4b92f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectmodel',
            name='projectapp__company_1b245e_idx',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='location',
            new_name='location_name',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='project_address',
            field=models.CharField(blank=True, help_text='e.g-> AkamIndustry10Days_V01/SPD6', max_length=256, null=True),
        ),
        migrations.AddIndex(
            model_name='projectmodel',
            index=models.Index(fields=['location_name'], name='projectapp__locatio_af5ace_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmodel',
            index=models.Index(fields=['company_name', 'location_name'], name='projectapp__company_e822ea_idx'),
        ),
    ]
