# Generated by Django 5.0 on 2025-07-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_projectmodel_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='image_description',
            field=models.FileField(blank=True, null=True, upload_to='pic_files', verbose_name='Image'),
        ),
    ]
