# Generated by Django 5.0 on 2025-08-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_projectmodel_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='lat',
            field=models.FloatField(default=35.0, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='lon',
            field=models.FloatField(default=50.0, verbose_name='lon'),
        ),
    ]
