# Generated by Django 5.0 on 2025-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_projectmodel_lat_projectmodel_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='lat',
            field=models.FloatField(verbose_name='lat'),
        ),
    ]
