# Generated by Django 5.0 on 2025-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_alter_projectmodel_lat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='lon',
            field=models.FloatField(verbose_name='lon'),
        ),
    ]
