# Generated by Django 5.0 on 2025-08-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_projectmodel_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='is_active',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_active?'),
        ),
    ]
