# Generated by Django 5.0 on 2025-08-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_projectmodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
