# Generated by Django 5.0 on 2025-08-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0015_alter_projectmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='is_active_now',
            field=models.BooleanField(default=False, editable=False, verbose_name='is_active_now'),
        ),
    ]
