# Generated by Django 5.0 on 2025-08-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0016_remove_projectmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
