# Generated by Django 5.0 on 2025-08-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0017_alter_projectmodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymodel',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='latest_pdf_path',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True, verbose_name='Latest PDF path'),
        ),
    ]
