# Generated by Django 5.0 on 2025-08-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_alter_companymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='latest_pdf_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Latest PDF path'),
        ),
    ]
