# Generated by Django 5.0 on 2025-08-30 10:19

import core.files_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0019_alter_projectmodel_latest_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='image_description',
            field=models.FileField(blank=True, null=True, upload_to=core.files_path.location_file_path, verbose_name='Image'),
        ),
    ]
